language: node_js
node_js:
- 8.9.4
before_install:
- openssl aes-256-cbc -K $encrypted_d879fb40751b_key -iv $encrypted_d879fb40751b_iv
  -in id_rsa.enc -out id_rsa -d
- chmod 600 ~/.ssh/id_rsa
after_success:
- ssh root@59.110.223.240  "./travis_build"
addons:
  ssh_known_hosts: 59.110.223.240