language: node_js
node_js:
- '8.9.4'
after_script:
- echo "-after  start-----------------------------------"
- scp -r -o StrictHostKeyChecking=no ./build 118.190.158.102:/root/app/praise
before_install:
- echo "-start-----------------------------------"
- openssl aes-256-cbc -K $encrypted_d9df02b07c62_key -iv $encrypted_d9df02b07c62_iv
  -in zhangyuan_key.enc -out ~/.ssh/zhangyuan_key -d
- chmod 600 ~/.ssh/zhangyuan_key
- eval $(ssh-agent)
- ssh-add ~/.ssh/zhangyuan_key
- cp .travis/ssh_config ~/.ssh/config
- chmod 600 ~/.ssh/config
- echo "-end-----------------------------------"