language: node_js
node_js:
- 8.9.4
before_install:
- openssl aes-256-cbc -K $encrypted_d879fb40751b_key -iv $encrypted_d879fb40751b_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- scp .travis/ssh_config ~/.ssh/config 
- chmod 600 ~/.ssh/config
script: true
after_success:
  - scp -r -o StrictHostKeyChecking=no app.js root@59.110.223.240:/root/test/
#- ssh root@59.110.223.240  "./travis_build"
addons:
  -ssh_known_hosts: "59.110.223.240"
